# Project level configuration
project:
  tz: "Asia/Kolkata"  # Trading timezone
  run_id_format: "YYYYMMDD-HHmm-<TAG>"  # Run identifier template

# Data label generation parameters
data:
  candle_time_convention: "end"  # allowed: start|end
  horizon_bars: 10  # default number of bars for default chart horizon
  horizons: [1, 3, 5, 10]  # Forecast horizons in bars
  neutral_epsilon_bp: 8  # abs return in basis points for ‘neutral’

# Evaluation settings
eval:
  coverage_tau: 0.70  # min confidence to take trades
  metrics: ["hit_rate_costed", "directional_acc_by_h", "sharpe", "sortino", "profit_factor", "mdd", "turnover"]  # Metrics to compute

# Explicit trading costs in basis points
costs:
  brokerage_bps: 3  # Broker commission
  stt_bps: 10  # Securities transaction tax
  gst_bps: 1.8  # Goods and services tax
  stamp_bps: 1  # Stamp duty
  exchange_bps: 3  # Exchange charges
  slippage_half_spread_bp: 2  # Half spread assumption
  impact_coeff: 0.15  # times qty/ADV

# Reinforcement learning hyper-parameters
rl:
  algo: "PPO_discrete"  # Algorithm identifier
  actions: ["Flat", "Long1", "Long2", "Short1", "Short2"]  # Discrete action space ordering
  turnover_lambda: 0.5  # Penalty on turnover
  dd_lambda: 0.2  # Penalty on drawdown
  kill_switch:
    max_daily_loss_pct: 2.0  # Kill-switch threshold
  seed: 42  # Deterministic seed

# Hyper-parameter optimisation settings
hpo:
  optuna:
    trials: 50  # Number of Optuna trials
    objective: "oos_sharpe"  # Study objective
