data:
  input_parquet_glob: "data/minute_bars/*.parquet"
  timezone: "Asia/Kolkata"
  symbol_col: "symbol"
  ts_col: "ts"
  ohlc_cols: ["open", "high", "low", "close"]
volatility:
  method: "ewma"
  span_minutes: 30
  min_sigma: 0.0005
cusum:
  k_sigma: 0.8
  drift: 0.0
  min_spacing_minutes: 10
triple_barrier:
  pt_k: 1.5
  sl_k: 1.5
  max_horizon_minutes: 120
  min_move_k: 0.4
  drop_ambiguous: true
splits:
  n_folds: 5
  embargo_minutes: 60
  backtest_blocks: 6
io:
  events_parquet: "artifacts/labels/events.parquet"
  labels_parquet: "artifacts/labels/labels.parquet"
  splits_json: "artifacts/labels/splits.json"
  quality_report_md: "artifacts/labels/quality_report.md"
reproducibility:
  seed: 42
